# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Sales Notifications"
client_id = "707ca16e6807f42e382f6d6171b31fc0"
application_url = "https://markers-afraid-exchanges-uh.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://markers-afraid-exchanges-uh.trycloudflare.com/auth/shopify/callback",
  "https://markers-afraid-exchanges-uh.trycloudflare.com/authSa/shopify/callback",
  "https://markers-afraid-exchanges-uh.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-sale-notifications.myshopify.com"
